package gts.trainningcourse.mockproject.utils

object Contacts {
    const val KEY_DARK_MODE = "key_mode"
    const val KEY_LOCATION = "key_location"
    const val KEY_LOGOUT = "key_log_out"
    const val CLICK_AGAIN = "Hãy click Login Button thêm 1 lần nữa"
    const val FAIL_LOGIN = "Tài khoản hoặc mật khẩu không đúng"
    const val KEY_ABOUT = "key_about"
    const val KEY_DELETE_ACCOUNT = "key_delete_acc"
    const val DIALOG_FRAGMENT_TAG = "dialog.fragment.tag"
    const val TITLE_DEF = "Sorry :3"
    const val MSG_DEF = "We will update it as soon as possible"
    const val TITLE_COMNHALAM = "Cơm nhà làm"
    const val TITLE_COCACOLA = "Coca Cola"
    const val TITLE_PEPSI = "Pepsi"
    const val TITLE_NUOCKHOANG = "Nước khoáng thiên nhiên"
    const val TITLE_MIY = "Mì ý"
    const val TITLE_MITRON = "Mì trộn"
    const val TITLE_MIXAO = "Phở xào"
    const val TITLE_PIZZA1 = "Pizza cỡ lớn"
    const val TITLE_PIZZA2 = "Pizza cỡ vừa"
    const val TITLE_PIZZA3 = "Pizza cỡ nhỏ"
    const val TITLE_COMRANG1 = "Cơm rang dưa bò"
    const val TITLE_COMRANG2 = "Cơm rang thập cẩm"
    const val TITLE_CHICKEN = "Gà không lối thoát"
    const val TITLE_FRIEDPOTATO1 = "Khoai tây chiên"
    const val TITLE_FRIEDPOTATO2 = "Khoai lang kén"


    const val NOTE_COMNHALAM = "Cơm nhà làm, cơm ngon như vợ nấu"
    const val NOTE_COCACOLA = "Một thương hiệu nổi tiếng đi cùng với những hương vị thật thanh mát"
    const val NOTE_MIY = "Mỳ ý được biến đến là một trong những món mì nổi tiếng trên thế giới"
    const val NOTE_PIZZA = "Pizza bạn nên gọi luôn hia cái vì một cái bạn ăn cả ngày cũng không đủ"
    const val NOTE_FRIEDPOTATO = "Khoai tây chiên món ăn vặt rất được yêu thích"
    const val NOTE_PHOXAO = "Nếu bạn muốn sự mới mẻ trong những thứ thân thuộc nhât, không cần đi đâu xa, phở xào sẽ giúp bạn"
    const val NOTE_COMRANG = "Cơm rang dưa bò được mệnh danh là món cơm bình dân, không chỉ vì sự thơm ngon mà còn không kén người ăn"
    const val NOTE_MITRON = "Mì trộn là thức ăn nhanh gọn và ít nóng hơn mì tôm thông thường."
    const val NOTE_NUOCKHOANG = "Cả thiên nhiên nằm ngọn trong tay bạn."
    const val NOTE_CHICKEN ="Đậm vị ngon, đậm vị lạ, gà không lối thoát ăn là mê"
    const val CATEGORY_PIZZA = "Pizza"
    const val CATEGORY_DRINK = "Drink"
    const val CATEGORY_NOODLE = "Noodle"
    const val CATEGORY_RICE = "Rice"
    const val CATEGORY_CHICKEN = "Chicken"
    const val CATEGORY_FRIEDPOTATO = "Fried Potato"
}